### ISSUE TITLE
markdown渲染问题

### ISSUE THREAD

**Issue by M0rtzz** [zhangyu1818/rsc-mdx#1]
markdown的引用块和警告框的渲染能更新一下吗：

原文：

![图片](https://github.com/zhangyu1818/rsc-mdx/assets/147259692/5a988dcd-cada-4f76-9f14-68316eb91c36)

![图片](https://github.com/zhangyu1818/rsc-mdx/assets/147259692/0ba361d3-bc69-49cc-9c32-cf07ec775157)

引用框会出现引号，警告框无法正常显示：

![图片](https://github.com/zhangyu1818/rsc-mdx/assets/147259692/b095428e-3b87-4152-af2d-de337fb1794b)

![图片](https://github.com/zhangyu1818/rsc-mdx/assets/147259692/3298c9d7-0a14-4a96-8ef3-042e1855c71c)

**Comment by zhangyu1818** [comment]
这是Github [Markdown扩展语法](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)，与标准Markdown不同且与此库无关，此库只是[mdx-js](https://github.com/mdx-js/mdx)的包装。

要在自己的Markdown中实现这个效果，可以使用插件，比如[这个](https://github.com/hyoban/remark-github-alerts)。

---

如果你指的是我博客里的话，已经实现了部分效果，你可能需要自定义样式：

- [语法解析](https://github.com/zhangyu1818/blog/blob/next14/src/markdown/plugins.ts)
- [自定义渲染](https://github.com/zhangyu1818/blog/blob/next14/src/markdown/components/alert.tsx)

提示：

1. 引号是CSS加的。
2. 根据标签类型渲染不同的Icon组件和样式。

用别的插件需要把这些都去掉。

**Comment by M0rtzz** [comment]
> 这是Github [Markdown扩展语法](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)，与标准Markdown不同且与此库无关，此库只是[mdx-js](https://github.com/mdx-js/mdx)的包装。
> 
> 要在自己的Markdown中实现这个效果，可以使用插件，比如[这个](https://github.com/hyoban/remark-github-alerts)。
> 
> 如果你指的是我博客里的话，已经实现了部分效果，你可能需要自定义样式：
> 
>     * [语法解析](https://github.com/zhangyu1818/blog/blob/next14/src/markdown/plugins.ts)
> 
>     * [自定义渲染](https://github.com/zhangyu1818/blog/blob/next14/src/markdown/components/alert.tsx)
> 
> 
> 提示：
> 
>     1. 引号是CSS加的。
> 
>     2. 根据标签类型渲染不同的Icon组件和样式。
> 
> 
> 用别的插件需要把这些都去掉。

![图片](https://github.com/zhangyu1818/rsc-mdx/assets/147259692/bbd2a8e5-7beb-416d-8ce2-30306179fc6d)

那这种局部代码块呢

**Comment by zhangyu1818** [comment]
大部分markdown库在不用插件的情况下，做的工作只是将markdown渲染成html，是不会改变内容的。

最终效果所有的样式都来源于css，你可以先在页面审查html，这些问题都和这个仓库没关系。
